/**
 * ElectroHub — Extended Categories Data for Categories Page
 * Adds Tools & Accessories + richer descriptions to existing categories.
 */

import type { Category, Brand } from '@/types';

// ─── All Categories (10 total) ────────────────────────────────────────────────
export const ALL_CATEGORIES: Category[] = [
  {
    id: 'cat-arduino',
    name: 'Arduino',
    slug: 'arduino',
    description: 'Official & compatible Arduino boards, shields, modules, and comprehensive starter kits for every skill level.',
    imageUrl: 'https://placehold.co/600x400/00979d/ffffff?text=Arduino',
    iconName: 'cpu',
    productCount: 47,
    status: 'active',
    sortOrder: 1,
    featuredColor: '#00979d',
  },
  {
    id: 'cat-rpi',
    name: 'Raspberry Pi',
    slug: 'raspberry-pi',
    description: 'Full-featured single-board computers for AI, ML, IoT, robotics, and embedded Linux projects.',
    imageUrl: 'https://placehold.co/600x400/c51a4a/ffffff?text=Raspberry+Pi',
    iconName: 'server',
    productCount: 38,
    status: 'active',
    sortOrder: 2,
    featuredColor: '#c51a4a',
  },
  {
    id: 'cat-esp32',
    name: 'ESP32 & ESP8266',
    slug: 'esp32',
    description: 'WiFi & Bluetooth enabled microcontrollers — the most versatile IoT development platforms available.',
    imageUrl: 'https://placehold.co/600x400/e7373b/ffffff?text=ESP32',
    iconName: 'wifi',
    productCount: 63,
    status: 'active',
    sortOrder: 3,
    featuredColor: '#e7373b',
  },
  {
    id: 'cat-sensors',
    name: 'Sensors',
    slug: 'sensors',
    description: 'Temperature, humidity, motion, pressure, gas, ultrasonic, and specialty environmental sensing modules.',
    imageUrl: 'https://placehold.co/600x400/16a34a/ffffff?text=Sensors',
    iconName: 'activity',
    productCount: 142,
    status: 'active',
    sortOrder: 4,
    featuredColor: '#16a34a',
  },
  {
    id: 'cat-displays',
    name: 'Displays',
    slug: 'displays',
    description: 'OLED, TFT, LCD, e-ink, and LED matrix display modules for every project output requirement.',
    imageUrl: 'https://placehold.co/600x400/0ea5e9/ffffff?text=Displays',
    iconName: 'monitor',
    productCount: 56,
    status: 'active',
    sortOrder: 5,
    featuredColor: '#0ea5e9',
  },
  {
    id: 'cat-motors',
    name: 'Motors',
    slug: 'motors',
    description: 'Stepper motors, servo motors, DC motors, brushless motors, encoders, and motor driver ICs.',
    imageUrl: 'https://placehold.co/600x400/7c3aed/ffffff?text=Motors',
    iconName: 'rotate-cw',
    productCount: 89,
    status: 'active',
    sortOrder: 6,
    featuredColor: '#7c3aed',
  },
  {
    id: 'cat-robotics',
    name: 'Robotics Kits',
    slug: 'robotics',
    description: 'Complete robot chassis, arm kits, SLAM robots, drones, and educational robotics platforms.',
    imageUrl: 'https://placehold.co/600x400/f97316/ffffff?text=Robotics',
    iconName: 'bot',
    productCount: 74,
    status: 'active',
    sortOrder: 7,
    featuredColor: '#f97316',
  },
  {
    id: 'cat-power',
    name: 'Power Modules',
    slug: 'power-modules',
    description: 'Buck converters, boost modules, battery management systems, solar chargers, and UPS modules.',
    imageUrl: 'https://placehold.co/600x400/ca8a04/ffffff?text=Power',
    iconName: 'zap',
    productCount: 61,
    status: 'active',
    sortOrder: 8,
    featuredColor: '#ca8a04',
  },
  {
    id: 'cat-tools',
    name: 'Tools',
    slug: 'tools',
    description: 'Soldering irons, oscilloscopes, multimeters, logic analyzers, hot air stations, and bench PSUs.',
    imageUrl: 'https://placehold.co/600x400/6366f1/ffffff?text=Tools',
    iconName: 'wrench',
    productCount: 83,
    status: 'active',
    sortOrder: 9,
    featuredColor: '#6366f1',
  },
  {
    id: 'cat-accessories',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Breadboards, jumper wires, resistors, capacitors, PCBs, connectors, and maker essentials.',
    imageUrl: 'https://placehold.co/600x400/94a3b8/334155?text=Accessories',
    iconName: 'layers',
    productCount: 215,
    status: 'active',
    sortOrder: 10,
    featuredColor: '#64748b',
  },
];

// ─── Featured / Promoted Categories ───────────────────────────────────────────
export interface FeaturedCategoryPromo {
  id: string;
  name: string;
  tagline: string;
  description: string;
  ctaText: string;
  href: string;
  gradient: string;
  accentColor: string;
  badgeText: string;
  imageText: string;
  productCount: number;
  topProducts: string[];
}

export const FEATURED_CATEGORY_PROMOS: FeaturedCategoryPromo[] = [
  {
    id: 'promo-arduino',
    name: 'Arduino Ecosystem',
    tagline: 'Official boards. Endless possibilities.',
    description: 'From the beginner-friendly UNO R4 to the powerful Portenta H7, explore the complete Arduino lineup and accessories.',
    ctaText: 'Explore Arduino',
    href: '/categories/arduino',
    gradient: 'linear-gradient(135deg, #00979d 0%, #006b70 100%)',
    accentColor: '#00979d',
    badgeText: '🔥 New: UNO R4 WiFi',
    imageText: '⚡',
    productCount: 47,
    topProducts: ['Arduino UNO R4 WiFi', 'Arduino Mega 2560', 'Arduino Nano Every', 'Arduino Starter Kit'],
  },
  {
    id: 'promo-rpi',
    name: 'Raspberry Pi Universe',
    tagline: 'The world\'s best SBC — now faster.',
    description: 'Raspberry Pi 5 is here with PCIe 2.0, dual 4K HDMI, and up to 8GB RAM. Build anything from a desktop PC to an AI camera.',
    ctaText: 'Shop Raspberry Pi',
    href: '/categories/raspberry-pi',
    gradient: 'linear-gradient(135deg, #c51a4a 0%, #8b1236 100%)',
    accentColor: '#c51a4a',
    badgeText: '🆕 RPi 5 In Stock',
    imageText: '🍓',
    productCount: 38,
    topProducts: ['Raspberry Pi 5 (8GB)', 'Raspberry Pi 4 (4GB)', 'RPi Pico W', 'Official Case Kit'],
  },
  {
    id: 'promo-sensors',
    name: 'Sensor Lab',
    tagline: 'Sense everything. Build smarter.',
    description: '142+ sensors for temperature, humidity, motion, gas, ultrasonic, IMU, LiDAR, and advanced environmental monitoring.',
    ctaText: 'Browse Sensors',
    href: '/categories/sensors',
    gradient: 'linear-gradient(135deg, #16a34a 0%, #0d7a31 100%)',
    accentColor: '#16a34a',
    badgeText: '✨ 142+ Products',
    imageText: '🔬',
    productCount: 142,
    topProducts: ['DHT22', 'MPU-6050', 'BMP280', 'HC-SR04 Ultrasonic'],
  },
];

// ─── Extended Brands for Categories Page ──────────────────────────────────────
export const ALL_BRANDS: Brand[] = [
  {
    id: 'brand-arduino',
    name: 'Arduino',
    slug: 'arduino',
    logoUrl: 'https://placehold.co/160x80/00979d/ffffff?text=Arduino',
    description: 'The world\'s leading open-source electronics platform for makers.',
    website: 'https://arduino.cc',
    productCount: 47,
    isFeatured: true,
    status: 'active',
    country: 'Italy',
  },
  {
    id: 'brand-rpi',
    name: 'Raspberry Pi',
    slug: 'raspberry-pi',
    logoUrl: 'https://placehold.co/160x80/c51a4a/ffffff?text=Raspberry+Pi',
    description: 'Affordable single-board computers for education and innovation.',
    website: 'https://raspberrypi.com',
    productCount: 38,
    isFeatured: true,
    status: 'active',
    country: 'UK',
  },
  {
    id: 'brand-espressif',
    name: 'Espressif',
    slug: 'espressif',
    logoUrl: 'https://placehold.co/160x80/e7373b/ffffff?text=Espressif',
    description: 'Leading provider of WiFi/Bluetooth SoCs and solutions.',
    website: 'https://espressif.com',
    productCount: 63,
    isFeatured: true,
    status: 'active',
    country: 'China',
  },
  {
    id: 'brand-seeed',
    name: 'Seeed Studio',
    slug: 'seeed-studio',
    logoUrl: 'https://placehold.co/160x80/16a34a/ffffff?text=Seeed',
    description: 'Open hardware manufacturer for makers and innovators worldwide.',
    website: 'https://seeedstudio.com',
    productCount: 112,
    isFeatured: true,
    status: 'active',
    country: 'China',
  },
  {
    id: 'brand-dfrobot',
    name: 'DFRobot',
    slug: 'dfrobot',
    logoUrl: 'https://placehold.co/160x80/1d4ed8/ffffff?text=DFRobot',
    description: 'Premium robotics and STEM education products.',
    website: 'https://dfrobot.com',
    productCount: 91,
    isFeatured: true,
    status: 'active',
    country: 'China',
  },
  {
    id: 'brand-adafruit',
    name: 'Adafruit',
    slug: 'adafruit',
    logoUrl: 'https://placehold.co/160x80/e91e8c/ffffff?text=Adafruit',
    description: 'High-quality open source hardware and educational electronics.',
    website: 'https://adafruit.com',
    productCount: 58,
    isFeatured: true,
    status: 'active',
    country: 'USA',
  },
  {
    id: 'brand-waveshare',
    name: 'Waveshare',
    slug: 'waveshare',
    logoUrl: 'https://placehold.co/160x80/0ea5e9/ffffff?text=Waveshare',
    description: 'Quality display modules and accessories for the maker community.',
    website: 'https://waveshare.com',
    productCount: 78,
    isFeatured: true,
    status: 'active',
    country: 'China',
  },
  {
    id: 'brand-sparkfun',
    name: 'SparkFun',
    slug: 'sparkfun',
    logoUrl: 'https://placehold.co/160x80/e14020/ffffff?text=SparkFun',
    description: 'Electronics components and tutorials for the maker generation.',
    website: 'https://sparkfun.com',
    productCount: 44,
    isFeatured: true,
    status: 'active',
    country: 'USA',
  },
];

// ─── Why Shop With Us (Categories page version) ───────────────────────────────
export const WHY_SHOP_FEATURES = [
  {
    icon: 'ShieldCheck',
    title: 'Genuine Products',
    description: 'Every product is sourced directly from authorized distributors. Zero counterfeits, always.',
    color: '#16a34a',
    bgColor: '#dcfce7',
    stat: '100%',
    statLabel: 'Genuine guarantee',
  },
  {
    icon: 'Truck',
    title: 'Fast Delivery',
    description: 'Same-day dispatch before 3 PM. Pan-India delivery to 550+ cities in 24–48 hours.',
    color: '#2563eb',
    bgColor: '#dbeafe',
    stat: '2 Days',
    statLabel: 'Average delivery',
  },
  {
    icon: 'Lock',
    title: 'Secure Payment',
    description: '256-bit SSL encryption. UPI, cards, net banking, wallets, and cash on delivery accepted.',
    color: '#7c3aed',
    bgColor: '#ede9fe',
    stat: '256-bit',
    statLabel: 'SSL encryption',
  },
  {
    icon: 'RotateCcw',
    title: 'Easy Returns',
    description: '15-day no-questions-asked returns. Instant replacement for any DOA (Dead on Arrival) products.',
    color: '#e7373b',
    bgColor: '#fee2e2',
    stat: '15 Days',
    statLabel: 'Return window',
  },
  {
    icon: 'Headphones',
    title: 'Expert Support',
    description: 'Our team of engineers and makers is available 9 AM–9 PM via chat, email, and phone.',
    color: '#0ea5e9',
    bgColor: '#e0f2fe',
    stat: '9AM–9PM',
    statLabel: 'Support hours',
  },
];
