/**
 * ElectroHub — Categories & Brands Mock Data
 */

import type { Category, Brand } from '@/types';

// ─── Featured Categories ───────────────────────────────────────────────────────
export const CATEGORIES: Category[] = [
  {
    id: 'cat-arduino',
    name: 'Arduino',
    slug: 'arduino',
    description: 'Official & compatible Arduino boards, shields, and starter kits.',
    imageUrl: 'https://placehold.co/400x300/00979d/ffffff?text=Arduino',
    iconName: 'cpu',
    productCount: 47,
    status: 'active',
    sortOrder: 1,
    featuredColor: '#00979d',
  },
  {
    id: 'cat-rpi',
    name: 'Raspberry Pi',
    slug: 'raspberry-pi',
    description: 'Single-board computers for AI, IoT, and Linux projects.',
    imageUrl: 'https://placehold.co/400x300/c51a4a/ffffff?text=Raspberry+Pi',
    iconName: 'server',
    productCount: 38,
    status: 'active',
    sortOrder: 2,
    featuredColor: '#c51a4a',
  },
  {
    id: 'cat-esp32',
    name: 'ESP32 / ESP8266',
    slug: 'esp32',
    description: 'WiFi & Bluetooth enabled microcontrollers for IoT.',
    imageUrl: 'https://placehold.co/400x300/e7373b/ffffff?text=ESP32',
    iconName: 'wifi',
    productCount: 63,
    status: 'active',
    sortOrder: 3,
    featuredColor: '#e7373b',
  },
  {
    id: 'cat-sensors',
    name: 'Sensors',
    slug: 'sensors',
    description: 'Temperature, motion, pressure, gas, and specialty sensors.',
    imageUrl: 'https://placehold.co/400x300/16a34a/ffffff?text=Sensors',
    iconName: 'activity',
    productCount: 142,
    status: 'active',
    sortOrder: 4,
    featuredColor: '#16a34a',
  },
  {
    id: 'cat-motors',
    name: 'Motors',
    slug: 'motors',
    description: 'Stepper, servo, DC motors and drivers for robotics.',
    imageUrl: 'https://placehold.co/400x300/7c3aed/ffffff?text=Motors',
    iconName: 'rotate-cw',
    productCount: 89,
    status: 'active',
    sortOrder: 5,
    featuredColor: '#7c3aed',
  },
  {
    id: 'cat-displays',
    name: 'Displays',
    slug: 'displays',
    description: 'OLED, TFT, LCD, and e-ink display modules.',
    imageUrl: 'https://placehold.co/400x300/0ea5e9/ffffff?text=Displays',
    iconName: 'monitor',
    productCount: 56,
    status: 'active',
    sortOrder: 6,
    featuredColor: '#0ea5e9',
  },
  {
    id: 'cat-robotics',
    name: 'Robotics',
    slug: 'robotics',
    description: 'Complete kits, chassis, arms, and robotic components.',
    imageUrl: 'https://placehold.co/400x300/f97316/ffffff?text=Robotics',
    iconName: 'bot',
    productCount: 74,
    status: 'active',
    sortOrder: 7,
    featuredColor: '#f97316',
  },
  {
    id: 'cat-power',
    name: 'Power Modules',
    slug: 'power-modules',
    description: 'Buck converters, boost modules, battery shields, and UPS.',
    imageUrl: 'https://placehold.co/400x300/ca8a04/ffffff?text=Power',
    iconName: 'zap',
    productCount: 61,
    status: 'active',
    sortOrder: 8,
    featuredColor: '#ca8a04',
  },
];

// ─── Brands ───────────────────────────────────────────────────────────────────
export const BRANDS: Brand[] = [
  {
    id: 'brand-arduino',
    name: 'Arduino',
    slug: 'arduino',
    logoUrl: 'https://placehold.co/160x80/00979d/ffffff?text=Arduino',
    coverUrl: 'https://placehold.co/400x200/00979d/ffffff?text=Arduino+Official',
    description: 'The world\'s leading open-source electronics platform.',
    website: 'https://arduino.cc',
    productCount: 47,
    isFeatured: true,
    status: 'active',
    country: 'Italy',
  },
  {
    id: 'brand-rpi',
    name: 'Raspberry Pi',
    slug: 'raspberry-pi',
    logoUrl: 'https://placehold.co/160x80/c51a4a/ffffff?text=Raspberry+Pi',
    coverUrl: 'https://placehold.co/400x200/c51a4a/ffffff?text=Raspberry+Pi',
    description: 'Affordable single-board computers changing the world.',
    website: 'https://raspberrypi.com',
    productCount: 38,
    isFeatured: true,
    status: 'active',
    country: 'UK',
  },
  {
    id: 'brand-espressif',
    name: 'Espressif',
    slug: 'espressif',
    logoUrl: 'https://placehold.co/160x80/e7373b/ffffff?text=Espressif',
    coverUrl: 'https://placehold.co/400x200/e7373b/ffffff?text=Espressif+Systems',
    description: 'Leading provider of WiFi/Bluetooth chips and solutions.',
    website: 'https://espressif.com',
    productCount: 63,
    isFeatured: true,
    status: 'active',
    country: 'China',
  },
  {
    id: 'brand-dfrobot',
    name: 'DFRobot',
    slug: 'dfrobot',
    logoUrl: 'https://placehold.co/160x80/1d4ed8/ffffff?text=DFRobot',
    coverUrl: 'https://placehold.co/400x200/1d4ed8/ffffff?text=DFRobot',
    description: 'Premium robotics and electronics education kits.',
    website: 'https://dfrobot.com',
    productCount: 91,
    isFeatured: true,
    status: 'active',
    country: 'China',
  },
  {
    id: 'brand-waveshare',
    name: 'Waveshare',
    slug: 'waveshare',
    logoUrl: 'https://placehold.co/160x80/0ea5e9/ffffff?text=Waveshare',
    coverUrl: 'https://placehold.co/400x200/0ea5e9/ffffff?text=Waveshare+Electronics',
    description: 'Quality display modules and accessories for makers.',
    website: 'https://waveshare.com',
    productCount: 78,
    isFeatured: true,
    status: 'active',
    country: 'China',
  },
  {
    id: 'brand-seeed',
    name: 'Seeed Studio',
    slug: 'seeed-studio',
    logoUrl: 'https://placehold.co/160x80/16a34a/ffffff?text=Seeed',
    coverUrl: 'https://placehold.co/400x200/16a34a/ffffff?text=Seeed+Studio',
    description: 'Open hardware manufacturer for makers and innovators.',
    website: 'https://seeedstudio.com',
    productCount: 112,
    isFeatured: true,
    status: 'active',
    country: 'China',
  },
];

// ─── Testimonials ──────────────────────────────────────────────────────────────
export interface Testimonial {
  id: string;
  name: string;
  role: string;
  company: string;
  avatar: string;
  rating: number;
  text: string;
  product: string;
}

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Arjun Sharma',
    role: 'IoT Engineer',
    company: 'TechBridge Solutions',
    avatar: 'https://placehold.co/80x80/2563eb/ffffff?text=AS',
    rating: 5,
    text: 'ElectroHub is my go-to for every project. The ESP32 boards arrive in 2 days and are always genuine. Their technical support team actually knows electronics — a refreshing change!',
    product: 'ESP32-S3 DevKit-C',
  },
  {
    id: 't2',
    name: 'Priya Nair',
    role: 'Robotics Research Scholar',
    company: 'IIT Bombay',
    avatar: 'https://placehold.co/80x80/c51a4a/ffffff?text=PN',
    rating: 5,
    text: 'Ordered 50 Raspberry Pi 5 boards for our lab and every single one worked flawlessly. Pricing was competitive and shipment tracking was excellent. Highly recommended for institutional purchases!',
    product: 'Raspberry Pi 5 (8GB)',
  },
  {
    id: 't3',
    name: 'Rohan Mehta',
    role: 'Freelance Maker',
    company: 'Self-employed',
    avatar: 'https://placehold.co/80x80/16a34a/ffffff?text=RM',
    rating: 5,
    text: 'The product quality is consistent and the packaging is excellent — no more dead-on-arrival sensors. The wishlist and compare features help me plan projects months in advance.',
    product: 'DHT22 Sensor Pack × 10',
  },
  {
    id: 't4',
    name: 'Sneha Kulkarni',
    role: 'STEM Educator',
    company: 'Vidyamandir Academy',
    avatar: 'https://placehold.co/80x80/7c3aed/ffffff?text=SK',
    rating: 5,
    text: 'We buy Arduino kits from ElectroHub for our student workshops. Stock is always available, bulk pricing is fair, and they always include proper invoices for institutional billing.',
    product: 'Arduino Starter Kit (Bulk)',
  },
  {
    id: 't5',
    name: 'Karan Joshi',
    role: 'Product Designer',
    company: 'Nexus Innovations',
    avatar: 'https://placehold.co/80x80/ca8a04/ffffff?text=KJ',
    rating: 4,
    text: 'Fast delivery, genuine parts, and the website makes it easy to find exactly what you need. The advanced search filters are a game-changer for component sourcing.',
    product: 'NEMA 17 Stepper Motor',
  },
  {
    id: 't6',
    name: 'Divya Menon',
    role: 'Electronics Hobbyist',
    company: 'Maker Community Pune',
    avatar: 'https://placehold.co/80x80/e7373b/ffffff?text=DM',
    rating: 5,
    text: 'The breadth of inventory is incredible — from basic resistors to advanced AI accelerator modules. Returns were hassle-free when I ordered the wrong component. Will keep shopping here.',
    product: 'Various Components',
  },
];

// ─── Why Choose ElectroHub ────────────────────────────────────────────────────
export const WHY_CHOOSE_FEATURES = [
  {
    icon: 'ShieldCheck',
    title: '100% Genuine Products',
    description: 'All products sourced directly from authorized distributors and manufacturers. Zero counterfeit guarantee.',
    color: '#16a34a',
    bgColor: '#dcfce7',
  },
  {
    icon: 'Truck',
    title: 'Fast Pan-India Delivery',
    description: 'Same-day dispatch for orders before 3 PM. Express delivery to 550+ cities within 24–48 hours.',
    color: '#2563eb',
    bgColor: '#dbeafe',
  },
  {
    icon: 'Headphones',
    title: 'Expert Technical Support',
    description: 'Our support team consists of engineers and hobbyists who understand your project requirements deeply.',
    color: '#7c3aed',
    bgColor: '#ede9fe',
  },
  {
    icon: 'RotateCcw',
    title: 'Hassle-Free Returns',
    description: '15-day return policy with no questions asked. Instant replacement for DOA (Dead on Arrival) products.',
    color: '#e7373b',
    bgColor: '#fee2e2',
  },
  {
    icon: 'Tag',
    title: 'Best Price Guarantee',
    description: 'Found it cheaper elsewhere? We will match the price. Exclusive deals and bundle discounts every week.',
    color: '#ca8a04',
    bgColor: '#fef3c7',
  },
  {
    icon: 'Award',
    title: 'Trusted by 50,000+ Makers',
    description: 'Over 50,000 engineers, students, and hobbyists across India trust ElectroHub for their projects.',
    color: '#0ea5e9',
    bgColor: '#e0f2fe',
  },
];
