# Generated by Django 4.2.23 on 2026-08-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.RemoveField(model_name='customuser', name='username'),
            migrations.RemoveField(model_name='customuser', name='groups'),
            migrations.RemoveField(model_name='customuser', name='user_permissions'),
            migrations.AlterField(model_name='customuser', name='phone', field=models.CharField(blank=True, db_column='phone_number', max_length=15, null=True)),
            migrations.AlterField(model_name='customuser', name='role', field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20)),
            migrations.AlterModelTable(name='customuser', table='accounts_user'),
        ],
    )]
