# Generated by Django 4.2.23 on 2026-08-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reconcile_legacy_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
